# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95fec04ed0b6719e18983cb2b5150dd6b9dd11d9e984f647a9487c5d15a3c8c6b3df04f41221c87a0a681fe2575391c5d5f4f47a080666eab13a7af5fd1abe38

test:
  secret_key_base: 0a0ca1d6e7b586a13c328881b3c72733bac7ab3a806ac16cfa323f2313e91b1e0efb9d894016df4e20b674ced843b1b646d5ff7dfa8b2ee468312335fac3bb56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
